### ISSUE TITLE
when pool expires it shouldn't remove free workloads

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfexplorer#172] opened 2020-09-24 15:41 UTC
When a pool expires it shouldn't delete free resources deployed on it

**Comment by zaibon** [comment] 2020-09-29 14:41
@LeeSmet you thought on this one ?

**Comment by LeeSmet** [comment] 2020-09-29 16:35
It should, however as I explained in my comment on that issue, "free resources"  are not actually free, and relying on them being free will cause breakage at some point. The eventual introduction of network resources will mean all primitives are paid, so this seems to be a non issue actually

**Comment by zaibon** [comment] 2020-09-29 16:59
Duplicate of #171

**Closed by zaibon** 2020-09-29 16:59 UTC
Labels: type_bug
